insert into roles values(44,'ADMIN');
insert into roles values(45,'NORMAL');
insert into users values(998,true,'manumaanowais809@gmail.com',true,'Numaan','Owais','DF0RHLU0DU6qRl2hIl+ybQ==','8096512816','default.png','abmo1122');
insert into users values(999,true,'160418itb103@gmail.com',true,'Rehaan','Owais','DF0RHLU0DU6qRl2hIl+ybQ==','8341278394','default.png','rehaan834');
insert into user_role values(998,45,998);
insert into user_role values(999,44,999);
insert into category values(998,'This quiz category is related to Programming Language','Programming Language');
insert into category values(999,'This quiz category is related to Aptitude Test','Aptitude Test');
insert into quiz values(998,true,'This quiz contains questions related to Java Basics',30,3,'Java Basics',998);
insert into quiz values(999,true,'This quiz contains questions related to Python Basics',20,2,'Python Basics',998);
insert into quiz values(1000,true,'This quiz contains questions related to Aptitude',30,3,'Aptitude Test',999);
insert into question values(998,'OOPS','What is java programming?','java1.png','OOPS','Function','Method','Collection',998);
insert into question values(999,'Exception','Which is not an OOPs concept?','java2.png','Encapsulation','Abstraction','Exception','Polymorphism',998);
insert into question values(1000,'myFunction','Select camelcase from below options.','java3.png','myfunction','MyFunction','myFunction','Myfunction',998);
insert into question values(1001,'myFunction','Select camelcase from below options.','python1.png','myfunction','MyFunction','myFunction','Myfunction',999);
insert into question values(1002,'Programming Language','What is Python?','python2.png','Object','Method','Programming Language','Function',999);
insert into question values(1003,'4','What is 2+2?','math1.png','2','3','4','1',1000);
insert into question values(1004,'8','What is 4+4?','math2.png','2','3','8','1',1000);
insert into question values(1005,'10','What is 2*5?','math3.png','2','3','10','1',1000);